config/routes.rb
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  resources :gbpnzd_m5s
  resources :gbpnzds
  mount Sidekiq::Web => '/sidekiq'
  resources :posts
  resources :images
  get 'signin', to: 'sessions#new'
  post 'signin', to: 'sessions#create'
  delete 'signout', to: 'sessions#destroy'
  get 'signup', to: 'users#new'
  match '/uploads/grid/image/attachment/:id/:filename' => 'gridfs#avatar_image', constraints: { filename: /avatar.*/ }, via: :get
  match '/uploads/grid/image/attachment/:id/:filename' => 'gridfs#thumb_image', constraints: { filename: /thumb.*/ }, via: :get
  match '/uploads/grid/image/attachment/:id/:filename' => 'gridfs#image', via: :get
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#index"
end

app/models/gbpnzd.rb
class Gbpnzd
  include Mongoid::Document
  include Mongoid::Timestamps
  field :epoch, type: Integer
  field :quote, type: BigDecimal

  after_create :m5

  def m5
    
  end
end

app/controllers/gbpnzds_controller.rb
class GbpnzdsController < ApplicationController
  before_action :set_gbpnzd, only: %i[ show edit update destroy ]

  # GET /gbpnzds or /gbpnzds.json
  def index
    @gbpnzds = Gbpnzd.all.order_by(created_at: :desc).limit(100)
  end

  # GET /gbpnzds/1 or /gbpnzds/1.json
  def show
  end

  # GET /gbpnzds/new
  def new
    @gbpnzd = Gbpnzd.new
  end

  # GET /gbpnzds/1/edit
  def edit
  end

  # POST /gbpnzds or /gbpnzds.json
  def create
    @gbpnzd = Gbpnzd.new(gbpnzd_params)

    respond_to do |format|
      if @gbpnzd.save
        format.html { redirect_to gbpnzd_url(@gbpnzd), notice: "Gbpnzd was successfully created." }
        format.json { render :show, status: :created, location: @gbpnzd }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @gbpnzd.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gbpnzds/1 or /gbpnzds/1.json
  def update
    respond_to do |format|
      if @gbpnzd.update(gbpnzd_params)
        format.html { redirect_to gbpnzd_url(@gbpnzd), notice: "Gbpnzd was successfully updated." }
        format.json { render :show, status: :ok, location: @gbpnzd }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @gbpnzd.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gbpnzds/1 or /gbpnzds/1.json
  def destroy
    @gbpnzd.destroy

    respond_to do |format|
      format.html { redirect_to gbpnzds_url, notice: "Gbpnzd was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gbpnzd
      @gbpnzd = Gbpnzd.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def gbpnzd_params
      params.require(:gbpnzd).permit(:epoch, :quote)
    end
end

app/helpers/gbpnzds_helper.rb
module GbpnzdsHelper
end

app/views/gbpnzds/_form.html.erb
<%= form_with(model: gbpnzd, class: "contents") do |form| %>
  <% if gbpnzd.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(gbpnzd.errors.count, "error") %> prohibited this gbpnzd from being saved:</h2>

      <ul>
        <% gbpnzd.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :epoch %>
    <%= form.number_field :epoch, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :quote %>
    <%= form.text_field :quote, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/gbpnzds/_gbpnzd.html.erb
<div id="<%= dom_id gbpnzd %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Epoch:</strong>
    <%= gbpnzd.created_at %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Quote:</strong>
    <%= gbpnzd.quote %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this gbpnzd", gbpnzd, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this gbpnzd', edit_gbpnzd_path(gbpnzd), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/gbpnzds/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing gbpnzd</h1>

  <%= render "form", gbpnzd: @gbpnzd %>

  <%= link_to "Show this gbpnzd", @gbpnzd, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to gbpnzds", gbpnzds_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/gbpnzds/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Gbpnzds</h1>
    <%= link_to 'New gbpnzd', new_gbpnzd_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="gbpnzds" class="min-w-full">
    <%= render @gbpnzds %>
  </div>
</div>

app/views/gbpnzds/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New gbpnzd</h1>

  <%= render "form", gbpnzd: @gbpnzd %>

  <%= link_to 'Back to gbpnzds', gbpnzds_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/gbpnzds/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @gbpnzd %>

    <%= link_to 'Edit this gbpnzd', edit_gbpnzd_path(@gbpnzd), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this gbpnzd', gbpnzd_path(@gbpnzd), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to gbpnzds', gbpnzds_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>